# OpenAI Configuration
#app.rest.base-url=https://jsonplaceholder.typicode.com
# REST API base URL for fetching data

#spring.ai.openai.chat.options.temperature=0.7
#spring.ai.openai.chat.options.model=gpt-3.5-turbo
#spring.ai.openai.api-key=${OPENAI_API_KEY:your-api-key-here}

# Groq Configuration
app.rest.base-url=https://jsonplaceholder.typicode.com

spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY: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}
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7

